StudentProfileManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static ,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('studentProfileApp.urls')),
]
urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

studentProfileApp/urls.py
from django.urls import path
from studentProfileApp import views


app_name='studentProfileApp'
urlpatterns = [
    path('',views.home,name='home'),
    path('add/',views.signUP,name='signUp'),
    path('studentDetails/<int:pk>/',views.studentDetails,name='studentDetails'),
    path('studentDelete/<int:pk>/',views.studentDelete,name='studentDelete'),
    path('editStudent/<int:pk>/',views.editStudent,name='editStudent'),
    
]

studentProfileApp/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    GENDER_CHOICES = [
        ('', 'Select a gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    ]
    RELIGION_CHOICES = [
        ('', 'Select a Religion'),
        ('Islam', 'Islam'),
        ('Hindu', 'Hindu'),
        ('Buddist', 'Buddist'),
    ]
    DEPARTMENT_CHOICES = [
        ('', 'Select a Department'),
        ('CSE', 'CSE'),
        ('Civil', 'Civil'),
        ('EEE', 'EEE'),
        ('ME', 'ME'),
        ('Chemistry', 'Chemistry'),
    ]
    name=models.CharField(max_length=30)
    email=models.EmailField(max_length=50)
    su_id=models.CharField(max_length=20)
    department =models.CharField(max_length=10, choices=DEPARTMENT_CHOICES,default='')
    phone=models.CharField(max_length=15)
    age=models.PositiveIntegerField()
    image=models.ImageField(upload_to='prof_pic')
    gender =models.CharField(max_length=10, choices=GENDER_CHOICES,default='')
    religion=models.CharField(max_length=10, choices=RELIGION_CHOICES,default='')
    address=models.TextField(max_length=100)

    def __str__(self):
        return self.name

    

studentProfileApp/forms.py
from django import forms
from studentProfileApp.models import Profile

class ProfileForm(forms.ModelForm):
    name=forms.CharField(label="Full Name",required=True)
    email=forms.EmailField(label="Email Address",required=True)
    su_id=forms.CharField(label="Student ID",required=True)
    phone=forms.CharField(label="Phone Number",required=True)
    class Meta:
        model=Profile
        fields=('name','email','su_id','department','phone','age','image','gender','religion','address')

studentProfileApp/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse
from studentProfileApp import models
from django.shortcuts import redirect
from studentProfileApp.forms import ProfileForm
from studentProfileApp.models import Profile
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib import messages
# Create your views here.
def home(request):
    if request.method=='GET':
        search=request.GET.get('src')
        if search:
            prof=Profile.objects.filter(name__icontains=search)
            if not prof:
                messages.warning(request, "Your account is about to expire.") 

        else:
            prof=Profile.objects.all()
            
    context = {'prof':prof}
    return render(request,'studentProfileApp/home.html',context)

def signUP(request):
    form=ProfileForm()
    registration=False
    if request.method=='POST':
        form=ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            registration=True
            return HttpResponseRedirect(reverse('studentProfileApp:home'))
    dict={'form':form,'registration':registration}
    return render(request,'studentProfileApp/signUp.html',context=dict)

def studentDetails(request, pk):
    student_id = Profile.objects.get(id=pk)
    context = {'student_id':student_id}
    return render(request, 'studentProfileApp/studentDetails.html', context)

def editStudent(request, pk):
    student_id = Profile.objects.get(id=pk)
    form = ProfileForm(instance=student_id )
    
    if request.method == "POST":
        form=ProfileForm(request.POST,request.FILES, instance=student_id)
        if form.is_valid():
            form.save()
            form=ProfileForm(instance=student_id)
            return HttpResponseRedirect(reverse('studentProfileApp:home'))
    context = {'form':form}
    return render(request, 'studentProfileApp/signUp.html', context)

def studentDelete(request, pk):
    student_data = Profile.objects.get(id=pk)
    student_data.delete()
    return HttpResponseRedirect(reverse('studentProfileApp:home'))

templates/base.html
<!DOCTYPE html>
{%load static%}
{%load crispy_forms_tags%}
<html lang="en">
<head>
  <title>{%block title_block%} All Students {%endblock%}</title>
  <meta charset="utf-8">


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link  href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body>
<div class="fixed-top">
 
  <nav class="navbar bg-dark navbar-dark justify-content-between">
    <div class="container-fluid " >
      <ul class=" form-inline ">
        <div class="nav-item active">
          <a class="nav-link" href="{%url 'studentProfileApp:home'%}">Home</a>       
        </div>
        <div class="nav-item ">
          <a class="nav-link" href="{%url 'studentProfileApp:signUp'%}">Sign Up</a>       
        </div>
       
      </ul>
      <form method="GET" class="form-inline" action="{%url 'studentProfileApp:home'%}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="src" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    
  </nav>

  </div>
<div class="container" style="padding-top: 30px;">
{% block body_block %}

{% endblock %}
<div class="fixed-bottom" >
<footer class="bg-dark text-center text-white">

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">SM Software Ltd.</a>
  </div>

</footer>
</div>

</div>

</body>
</html>





  

templates/studentProfileApp/complete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="5; url={% url 'studentProfileApp:home' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Payment Status</title>
</head>
<body>
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</body>
</html>

templates/studentProfileApp/home.html
{% extends 'base.html' %}
{%load crispy_forms_tags%}

{% block body_block %}
<br>
<br>

<h5>All Students</h5>
<div class="row">
 
    {% for data in prof %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      
      <div class="card " style="margin-bottom: 10px ;margin-top: 20px">
        <div class="card-body">
            <img src="/media/{{data.image}}" style="width:100%; height:200px;">
            <div class="card-body">
              <h6 class="card-title">{{data.name}}</h6>
              <a href="{% url 'studentProfileApp:studentDetails' pk=data.pk %}" class="btn btn-primary">More Details</a>
            </div>
        </div>
      </div>
     
    </div>
    {%endfor%}
   
     
  </div>







{% endblock %}

templates/studentProfileApp/signUp.html
{% extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title_block%}Sign Up {%endblock%}
{% block body_block %}
{%if registered%}
<h3>Update Musician</h3>

<form method="POST" enctype="multipart/form-data">
{%csrf_token%}
{{form|crispy}}
<input type="submit" name="submit" value="Update" class="btn btn-warning btn-sm">
</form>
<div class="alert alert-success">
    Account Created Successfully !! <a href="">Login Here</a>
</div>
{%else%}

<h2>Create New Account </h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>

</form>
<br>

<p> Already Have an Account ? <a href="">Login Here</a></p>
{%endif%}

{%endblock%}

templates/studentProfileApp/studentDetails.html
{% extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title_block%}Sign Up {%endblock%}
{% block body_block %}

<div class="col d-flex justify-content-center">
    <div class="card mb-3" style="max-width: 540px; margin-top: 40px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="/media/{{student_id.image}}" style="width:100%; height:200px;">
        </div>
          <div class="col-md-8">
            <div class="card-body">
              <h4 class="card-title">{{student_id.name}}</h4>
              <p class="card-text">Email Address : {{student_id.email}}</p>
              <p class="card-text">Student ID : {{student_id.su_id}}</p>
              <p class="card-text">Department : {{student_id.department}}</p>
              <p class="card-text">Phone Number : {{student_id.phone}}</p>
              <p class="card-text">Gender : {{student_id.gender}}</p>
              <p class="card-text">Religion : {{student_id.religion}}</p>
              <p class="card-text">Address : {{student_id.address}}</p>
              
            </div>
          </div>
          
        </div>
        <div class="card-footer text-muted">
            <a href="{% url 'studentProfileApp:editStudent' pk=student_id.pk %}" class="btn btn-success">Update</a>

            <a href="{% url 'studentProfileApp:studentDelete' pk=student_id.pk %}" class="btn btn-danger">Delete</a>

          </div>
      </div>

</div>

    

{%endblock%}